version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - run: npm run setup
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/node_modules

  test:
    <<: *defaults
    
    steps:
      - checkout
      - restore_cache:
          key: key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - run: npm run setup
      - run: npm run test

workflows:
  ssw:
    jobs:
      - build
      - test:
          requires:
            - build